name: "Build Extension"

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install dependencies
        run: |
          if [ -d "ent-ecole-maternelle" ]; then cd ent-ecole-maternelle; fi
          npm install

      - name: Build the extension
        run: |
          if [ -d "ent-ecole-maternelle" ]; then cd ent-ecole-maternelle; fi
          # Build Chrome
          npm run build
          # Build Firefox
          npm run build -- --target=firefox-mv2

      # NOUVEAU : On crée le ZIP manuellement pour éviter le problème de dossier
      - name: Zip Firefox Build Correctly
        run: |
          # On va dans le dossier, et on zippe le contenu (.)
          if [ -d "ent-ecole-maternelle" ]; then cd ent-ecole-maternelle; fi
          cd build/firefox-mv2-prod
          zip -r ../firefox-FINAL.zip .

      - name: Upload Chrome Artifact
        uses: actions/upload-artifact@v4
        with:
          name: chrome-extension
          path: |
            build/chrome-mv3-prod
            ent-ecole-maternelle/build/chrome-mv3-prod

      - name: Upload Firefox Artifact
        uses: actions/upload-artifact@v4
        with:
          name: firefox-extension-FINAL
          # On télécharge le ZIP qu'on vient de créer proprement
          path: |
            build/firefox-FINAL.zip
            ent-ecole-maternelle/build/firefox-FINAL.zip
