name: "Build Extension"

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Clean Install Dependencies
        run: |
          if [ -d "ent-ecole-maternelle" ]; then cd ent-ecole-maternelle; fi
          # 1. On supprime le fichier de verrouillage qui cause souvent des conflits
          rm -f package-lock.json
          # 2. On installe sans les modules optionnels (comme le watcher qui plante)
          npm install --no-optional

      - name: Build the extension
        run: |
          if [ -d "ent-ecole-maternelle" ]; then cd ent-ecole-maternelle; fi
          # Build Chrome
          npm run build
          # Build Firefox
          npm run build -- --target=firefox-mv2

      - name: Zip Firefox Build Correctly
        run: |
          if [ -d "ent-ecole-maternelle" ]; then cd ent-ecole-maternelle; fi
          cd build/firefox-mv2-prod
          zip -r ../firefox-FINAL.zip .

      - name: Upload Chrome Artifact
        uses: actions/upload-artifact@v4
        with:
          name: chrome-extension
          path: |
            build/chrome-mv3-prod
            ent-ecole-maternelle/build/chrome-mv3-prod

      - name: Upload Firefox Artifact
        uses: actions/upload-artifact@v4
        with:
          name: firefox-extension-FINAL
          path: |
            build/firefox-FINAL.zip
            ent-ecole-maternelle/build/firefox-FINAL.zip
